export type OfferCategory = 'all' | 'video' | 'click' | 'install' | 'survey' | 'daily'

export interface Offer {
  id: string
  title: string
  description: string
  category: Exclude<OfferCategory, 'all'>
  points: number
  estimatedTime: string
  sponsor: string
  difficulty: 'easy' | 'medium' | 'hard'
  featured?: boolean
  cooldownHours: number
}

export const offers: Offer[] = [
  // Daily bonus
  {
    id: 'daily-checkin',
    title: 'Daily Check-In Bonus',
    description: 'Log in every day and collect your free daily bonus points. Resets every 24 hours.',
    category: 'daily',
    points: 10,
    estimatedTime: '5 sec',
    sponsor: 'FreeBucks',
    difficulty: 'easy',
    featured: true,
    cooldownHours: 24,
  },
  // Video ads
  {
    id: 'video-1',
    title: 'Watch a Short Video Ad',
    description: 'Watch a 30-second sponsored video ad all the way through to earn your points.',
    category: 'video',
    points: 15,
    estimatedTime: '30 sec',
    sponsor: 'Various Brands',
    difficulty: 'easy',
    featured: true,
    cooldownHours: 1,
  },
  {
    id: 'video-2',
    title: 'Watch a 60-Second Ad',
    description: 'Watch a full 60-second video advertisement without skipping.',
    category: 'video',
    points: 25,
    estimatedTime: '1 min',
    sponsor: 'Premium Advertisers',
    difficulty: 'easy',
    cooldownHours: 2,
  },
  {
    id: 'video-3',
    title: 'Watch a Product Review Video',
    description: 'Watch a 2-minute product review video from our sponsor and answer one quick question.',
    category: 'video',
    points: 40,
    estimatedTime: '2 min',
    sponsor: 'ShopBrands',
    difficulty: 'easy',
    cooldownHours: 4,
  },
  {
    id: 'video-4',
    title: 'Watch a Movie Trailer',
    description: 'Watch an upcoming movie trailer and give a one-click rating.',
    category: 'video',
    points: 20,
    estimatedTime: '2 min',
    sponsor: 'EntertainCo',
    difficulty: 'easy',
    cooldownHours: 6,
  },
  {
    id: 'video-5',
    title: 'Watch a Sponsored News Briefing',
    description: 'Watch a 90-second sponsored news briefing from our media partner.',
    category: 'video',
    points: 30,
    estimatedTime: '90 sec',
    sponsor: 'NewsNetwork',
    difficulty: 'easy',
    cooldownHours: 6,
  },
  // Banner ad clicks
  {
    id: 'click-1',
    title: "Visit a Sponsor's Website",
    description: "Click through to a sponsor's landing page and spend 30 seconds exploring their offer.",
    category: 'click',
    points: 5,
    estimatedTime: '30 sec',
    sponsor: 'Web Advertisers',
    difficulty: 'easy',
    cooldownHours: 1,
  },
  {
    id: 'click-2',
    title: 'View a Featured Deal',
    description: "Visit a sponsor's page and browse their featured promotion for 45 seconds.",
    category: 'click',
    points: 8,
    estimatedTime: '45 sec',
    sponsor: 'Deal Partners',
    difficulty: 'easy',
    cooldownHours: 2,
  },
  {
    id: 'click-3',
    title: 'Browse a Partner Store',
    description: 'Visit a partner e-commerce store and view at least 3 product pages.',
    category: 'click',
    points: 12,
    estimatedTime: '1 min',
    sponsor: 'RetailPartners',
    difficulty: 'easy',
    cooldownHours: 4,
  },
  // App installs
  {
    id: 'install-1',
    title: 'Download a Free Mobile Game',
    description: 'Install a free mobile game and reach level 3 to unlock your reward points.',
    category: 'install',
    points: 200,
    estimatedTime: '15 min',
    sponsor: 'GameStudio',
    difficulty: 'medium',
    featured: true,
    cooldownHours: 9999,
  },
  {
    id: 'install-2',
    title: 'Try a Personal Finance App',
    description: 'Download and create a free account on a top-rated finance tracking app.',
    category: 'install',
    points: 350,
    estimatedTime: '10 min',
    sponsor: 'FinanceApp',
    difficulty: 'medium',
    cooldownHours: 9999,
  },
  {
    id: 'install-3',
    title: 'Install a Shopping Rewards App',
    description: 'Install a cashback shopping app and browse for 2 minutes.',
    category: 'install',
    points: 150,
    estimatedTime: '5 min',
    sponsor: 'ShopEasy',
    difficulty: 'easy',
    cooldownHours: 9999,
  },
  // Surveys
  {
    id: 'survey-1',
    title: 'Quick Opinion Survey',
    description: 'Share your opinion in a 3-minute survey about everyday consumer products.',
    category: 'survey',
    points: 50,
    estimatedTime: '3 min',
    sponsor: 'ResearchCo',
    difficulty: 'easy',
    cooldownHours: 24,
  },
  {
    id: 'survey-2',
    title: 'Consumer Preferences Survey',
    description: 'Help major brands understand consumers better with this 5-minute survey.',
    category: 'survey',
    points: 80,
    estimatedTime: '5 min',
    sponsor: 'MarketInsights',
    difficulty: 'medium',
    cooldownHours: 24,
  },
  {
    id: 'survey-3',
    title: 'Tech Usage Survey',
    description: 'Tell us about your technology and app habits in a short 4-minute survey.',
    category: 'survey',
    points: 60,
    estimatedTime: '4 min',
    sponsor: 'TechPulse',
    difficulty: 'easy',
    cooldownHours: 48,
  },
]
